---
id: modolabs/modo_nova_light_components
description: Nova Southeastern University Components - light
license: commercial
version: 1.0.0
require:
    kurogo/kurogo-core:
    -   '2.1.*'
    -   '2.2.*'
...
