---
common:

    # This section only applies when this module is configured as list- or springboard-style layout
    home_hero_image_src: logo-home.png
    home_hero_image_width: 100%
    home_hero_image_height: auto
    home_hero_image_max_width: 560px
    home_hero_image_max_height: none
    home_hero_image_padding: 6px 0 34px 0
    home_hero_image_background_color: '#FFFFFF'
    home_hero_image_alignment: center

    # This section only applies when this module is configured as springboard-style layout
    content_navigation_grid_icon_set: mono-white
    content_navigation_grid_icon_size: "120"
    content_navigation_grid_utility_icon_set: mono-white
    content_navigation_grid_utility_icon_size: "60"

    # This section only applies when this module is configured as list-style layout
    content_navigation_list_icon_set: mono-white
    content_navigation_list_icon_size: "120"
    content_navigation_list_utility_icon_set: mono
    content_navigation_list_utility_icon_size: "60"

    styles:
        kgoui_page: # Styling for home page's body background
            index:
                body_background_color: null        # Entire page background color
                body_background_image: null          # Entire page background image
                body_background_position: top left   # CSS background-position for the body background image (if specified); per CSS syntax
                body_background_repeat: no-repeat       # CSS background-repeat for the body background image (if specified); repeat | repeat-x | repeat-y | no-repeat
                body_background_size: 100% auto           # Entire page background image size (per CSS syntax)
                body_background_attachment: scroll   # CSS background-attachment for the body background image (if specified); scroll | fixed
                footer_text_color: null            # Color of text and text links in page footer, including 'Back to Top' and copyright notice.
        kgoui_list_navigation: # This section only applies when this module is configured as list-style layout (but not to the Text (basic) device class, which always gets the app-wide styling).
            primary:
                heading_text_color: null
                background_color: null # Background color for primary navigation lists. Set to null to default to global focal_background_color.
                border_color: null
            utility:
                heading_text_color: null
                background_color: null # Background color for utility-class navigation lists. Set to null to default to global focal_background_color.
                border_color: null
            login:
                background_color: rgba(9,80,148,0.6) # Background color for login navigation lists within the page body. Set to null to default to global focal_background_color.
                border_color: '#447ff5'
            settings:
                background_color: rgba(9,80,148,0.6) # Background color for settings navigation lists within the page body. Set to null to default to global focal_background_color.
                border_color: '#447ff5'
            favorites:
                background_color: null
                border_color: null
                heading_text_color: null
        kgoui_list_item_navigation:
            primary:      # Styling for primary module list(s). This section only applies when this module is configured as list-style layout (but not to the Text (basic) device class, which always gets the app-wide styling).
                title_font_family: null
                title_font_size: 1.125rem
                title_line_height: 1.25em
                text_color: null
                action_icon_color: null
            utility:      # Styling for utility-class module list(s). This section only applies when this module is configured as list-style layout (but not to the Text (basic) device class, which always gets the app-wide styling).
                title_font_family: null
                title_font_size: 1.125rem
                title_line_height: 1.25em
                text_color: null
                action_icon_color: null
            login:      # Styling for login link. This section applies to both list- and springboard-style layouts (but not to the Text (basic) device class, which always gets the app-wide styling).
                text_color: '#FFFFFF'
                action_icon_color: '#FFFFFF'
            settings:
                text_color: '#FFFFFF'
                action_icon_color: '#FFFFFF'
        kgoui_grid_navigation: # This section only applies when this module is configured as springboard-style layout.
            primary:    # Styling for primary module springboard section(s).
                background_color: rgba(9,80,148,0.6)  # Background color behind primary module springboard section(s).
                section_divider: '1px solid #447ff5'     # Border style below primary module springboard section(s). Use CSS compact notation. Applies to border-bottom for the containing <div>.
                margin_bottom: null
            utility:    # Styling for utility-class module springboard section(s).
                background_color: null
                section_divider: null     # Border style below utility-class module springboard section(s). Use CSS compact notation. Applies to border-bottom for the containing <div>.
                margin_bottom: null
            favorites:
                background_color: null
                section_divider: null
                heading_text_color: null    # Text color for "My Favorite Modules" section heading - MUST contrast with home screen background color.
                margin_bottom: 1rem
        kgoui_grid_item_navigation: # This section only applies when this module is configured as springboard-style layout.
            default:
                springboard_highlight_background_color: null    # Tap highlight color for springboard items
                text_color: null
            primary:
                text_color: '#FFFFFF'
                title_font_size: null   # Font size for springboard item titles. Often specified (larger) just for large device class, below.
                subtitle_font_size: null   # Font size for springboard item subtitles. Often specified (larger) just for large device class, below.
                line_height: null   # Line height (vertical text spacing) for springboard item titles and subtitles. Often specified (larger) just for large device class, below.
            utility:
                text_color: '#FFFFFF'
                title_font_size: null   # Font size for springboard item titles. Often specified (larger) just for large device class, below.
                subtitle_font_size: null   # Font size for springboard item subtitles. Often specified (larger) just for large device class, below.
                line_height: null   # Line height (vertical text spacing) for springboard item titles and subtitles. Often specified (larger) just for large device class, below.

small: # Styling for modern small-screen devices e.g., smartphones.
    styles:
        kgoui_page:
            index:  # To specify home page background styling specific to modern small-screen devices, delete this '{}', then copy and paste some or all of the corresponding parameters from the common section above.
                body_background_color: '#1e29a5'        # Entire page background color
                body_background_image: /bg_home.jpg          # Entire page background image
                body_background_position: top center   # CSS background-position for the body background image (if specified); per CSS syntax
                body_background_repeat: no-repeat       # CSS background-repeat for the body background image (if specified); repeat | repeat-x | repeat-y | no-repeat
                body_background_size: 100% auto           # Entire page background image size (per CSS syntax)
                body_background_attachment: fixed   # CSS background-attachment for the body background image (if specified); scroll | fixed
                footer_text_color: '#478cfa'            # Color of text and text links in page footer, including 'Back to Top' and copyright notice.

large: # Styling for tablets, laptops, and desktop computers.
    # Styling for portlets is set in the theme's app-wide theme file (common/config/theme.yaml).
    styles:
        kgoui_page:
            index: {} # To specify home page background styling specific to large-screen devices, delete this '{}', then copy and paste some or all of the corresponding parameters from the common section above.
        kgoui_grid_item_navigation: # This section only applies when this module is configured as springboard-style layout.
            primary:
                title_font_size: null   # Font size for springboard item titles
                subtitle_font_size: null   # Font size for springboard item subtitles
                line_height: null   # Line height (vertical text spacing) for springboard item titles and subtitles
            utility:
                title_font_size: null   # Font size for springboard item titles
                subtitle_font_size: null   # Font size for springboard item subtitles
                line_height: null   # Line height (vertical text spacing) for springboard item titles and subtitles


text:   # Styling for basic/text-based devices. Home-screen theming for this device class is very limited.
    home_hero_image_src: logo-home.gif
    home_hero_image_width: 160px
    home_hero_image_height: 64px
    home_hero_image_max_width: 160px
    home_hero_image_max_height: 64px
    home_hero_image_padding: 0;
    home_hero_image_background_color: '#004e96'
    home_hero_image_alignment: center

...
